language: node_js

node_js:
  - '7'

cache:
  directories:
    - node_modules
    - .nvm

script:
  - npm run monika -- --push-changes
  - npm test


notifications:
  slack: veckopengen:uRAtf0cYPUxlDqTDPBzSEa8R#travis-non-tech
